version: '3'
services:
  autoshift:
    container_name: autoshift
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - torrents 
    volumes:
      - ${BASE_MEDIA}:${BASE_MEDIA}
    environment:
      - TR_PATH=${TR_PATH}
      - JF_MOVIES=${JF_MOVIES}
      - JF_SHOWS=${JF_SHOWS}
      - TR_HOST_IP=${TR_HOST_IP}
      - TR_HOST_PORT=${TR_HOST_PORT}
      - TR_USER=${TR_USER}
      - TR_PASS=${TR_PASS}
      - LOG_LEVEL=${LOG_LEVEL}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - VERBOSE=${VERBOSE}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TR_PATH=${TR_PATH}
        - JF_MOVIES=${JF_MOVIES}
        - JF_SHOWS=${JF_SHOWS}
        - TR_HOST_IP=${TR_HOST_IP}
        - TR_HOST_PORT=${TR_HOST_PORT}
        - TR_USER=${TR_USER}
        - TR_PASS=${TR_PASS}
        - LOG_LEVEL=${LOG_LEVEL}
        - CRON_SCHEDULE=${CRON_SCHEDULE}
        - VERBOSE=${VERBOSE}
networks:
  torrents:
    external: true
